### ISSUE TITLE
pip installation on remote server throws package not found error

### ISSUE THREAD

**Issue by trejas** [nhedlund/intrinio#1]
```
remote:        Collecting intrinio==0.1.14 (from -r /tmp/build_e74cdbc82006a71a2a1e42669e8f527a/requirements.txt (line 6))
remote:          Downloading intrinio-0.1.14.tar.gz
remote:            Complete output from command python setup.py egg_info:
remote:            Traceback (most recent call last):
remote:              File "<string>", line 1, in <module>
remote:              File "/tmp/pip-build-wysyxkzd/intrinio/setup.py", line 9, in <module>
remote:                import pypandoc
remote:            ModuleNotFoundError: No module named 'pypandoc'
remote:
remote:            ----------------------------------------
remote:        Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wysyxkzd/intrinio/
remote:  !     Push rejected, failed to compile Python app.
```

**Comment by nhedlund** [comment]
Should be fixed in 0.1.15
